#!/usr/bin/env bash
# Brings the standalone yield and profit calculator
# (https://github.com/vivian4fb/oxyniti-yield-calc) onto oxyniti.com as the
# /yield-calculator page -- Pages/YieldCalculator.razor, inside the site's own
# layout, header and <Footer />.
#
# The calculator is plain HTML/CSS/JS with its own model tests and a Python
# oracle; its JS is shipped unchanged so those tests keep covering exactly the
# code that runs. Never hand-edit the generated output below -- change the
# calculator repo (or scripts/yield-calculator/), then re-run this script.
#
# Usage:
#   scripts/sync-yield-calculator.sh [<commit-sha>]   (default: the pinned REF below)
#
# Output:
#   wwwroot/yield-calculator/        the calculator's js/, data/, vendor/, assets/
#                                    (loaded by wwwroot/js/yieldCalculator.js)
#     css/styles.scoped.css          its stylesheet, every rule scoped under .yc
#                                    (scripts/yield-calculator/scope-css.mjs)
#     site/site-theme.css            oxyniti.com palette (scripts/yield-calculator/)
#   Pages/YieldCalculatorMarkup.g.cs the page body, as a C# string the Razor page
#                                    renders. Derived from the calculator's
#                                    index.html:
#     - its own header is dropped (the site header replaces it); the language
#       select and theme button ui.js requires are kept, hidden
#     - its footer is dropped (the site <Footer /> replaces it) but its
#       data-sources list is kept (scripts/yield-calculator/data-sources.html)
#       -- the ODbL boundary data requires that attribution on the page
#     - <main> becomes <div class="yc-main"> (the layout already has a <main>)
#     - role="status" is parked as data-yc-role="status" and restored by
#       yieldCalculator.js: tools/Prerender treats [role="status"] as a page
#       still loading and would refuse to capture this route
set -euo pipefail

REPO_URL="https://github.com/vivian4fb/oxyniti-yield-calc.git"
REF="${1:-e1e154ebe6a6fbc65b553613b5dfbf4667ce7efe}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$ROOT/wwwroot/yield-calculator"
SITE_SRC="$ROOT/scripts/yield-calculator"
MARKUP_CS="$ROOT/Pages/YieldCalculatorMarkup.g.cs"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git clone --quiet "$REPO_URL" "$TMP/calc"
git -C "$TMP/calc" checkout --quiet "$REF"
SHA="$(git -C "$TMP/calc" rev-parse HEAD)"
SRC="$TMP/calc/site"

# Empty the folder rather than delete it: on Windows a running `dotnet run`
# holds the directory itself open, and removing it fails.
mkdir -p "$DEST"
find "$DEST" -mindepth 1 -delete
cp -R "$SRC/js" "$SRC/data" "$SRC/vendor" "$SRC/assets" "$DEST/"
mkdir -p "$DEST/css" "$DEST/site"
node "$SITE_SRC/scope-css.mjs" "$SRC/css/styles.css" "$DEST/css/styles.scoped.css"
cp "$SITE_SRC/site-theme.css" "$DEST/site/"

SOURCES_TEMPLATE="$SITE_SRC/data-sources.html" SHA="$SHA" REPO_URL="$REPO_URL" \
perl -0e '
    local $/; my $html = <STDIN>;
    sub need { my ($ok, $what) = @_; die "error: $what\n" unless $ok; }

    my ($body) = $html =~ /<body>(.*?)<script\b/s;
    need(defined $body, "no <body> content before the first <script>");

    my ($sources) = $body =~ /(<ul id="data-sources">.*?<\/ul>)/s;
    need(defined $sources, "no data-sources list in the calculator footer");
    open(my $fh, "<", $ENV{SOURCES_TEMPLATE}) or die "error: cannot read $ENV{SOURCES_TEMPLATE}\n";
    my $section = <$fh>; close $fh;
    need($section =~ s/\{\{DATA_SOURCES\}\}/$sources/, "data-sources template has no {{DATA_SOURCES}}");

    my ($select) = $body =~ /(<select id="lang-select".*?<\/select>)/s;
    need(defined $select, "no #lang-select in the calculator header");
    my $hidden = "<div hidden>$select<button id=\"theme-toggle\" type=\"button\"></button></div>";

    need(($body =~ s/<header class="site-header">.*?<\/header>/$hidden/s) == 1, "expected one calculator header");
    need(($body =~ s/<footer class="site-footer">.*?<\/footer>/$section/s) == 1, "expected one calculator footer");
    need(($body =~ s/<main>/<div class="yc-main">/) == 1 && ($body =~ s/<\/main>/<\/div>/) == 1, "expected one <main>");
    $body =~ s/\srole="status"/ data-yc-role="status"/g;
    need($body !~ /"""""/, "markup contains a 5-quote run; widen the C# raw string");
    $body =~ s/^\s+|\s+$//g;

    print "// <auto-generated>\n";
    print "// Generated by scripts/sync-yield-calculator.sh from $ENV{REPO_URL} at $ENV{SHA}.\n";
    print "// Do not edit: re-run the script instead.\n";
    print "// </auto-generated>\n";
    print "namespace Oxyniti.Pages;\n\n";
    print "internal static class YieldCalculatorMarkup\n{\n";
    print "    public const string Html = \"\"\"\"\"\n$body\n\"\"\"\"\";\n}\n";
' < "$SRC/index.html" > "$MARKUP_CS"

printf 'Source: %s\nCommit: %s\nSynced by scripts/sync-yield-calculator.sh -- do not edit files here by hand.\n' \
    "$REPO_URL" "$SHA" > "$DEST/SOURCE.txt"

echo "Synced $REPO_URL@$SHA into wwwroot/yield-calculator/ and Pages/YieldCalculatorMarkup.g.cs"
