// Scopes the calculator's stylesheet to its container on the Blazor page
// (Pages/YieldCalculator.razor renders it inside <div id="yc-root" class="yc">),
// so its resets and element rules (*, body, h1, a, .container, .btn ...) cannot
// leak into the site's header and footer.
//
//   node scripts/yield-calculator/scope-css.mjs <in.css> <out.css>
//
// Every selector gets a ".yc " prefix; the document-level ones (:root, html,
// body) become ".yc" itself, so the calculator's design tokens and base
// colours land on the container. @media blocks are recursed into. The input is
// the calculator's own hand-written CSS -- no @keyframes/@font-face/@import --
// and the script fails loudly on any at-rule it does not handle.
import fs from "node:fs";

const [, , input, output] = process.argv;
const css = fs.readFileSync(input, "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
const SCOPE = ".yc";

function splitTopLevel(text, sep) {
  const parts = [];
  let depth = 0, quote = null, start = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quote) { if (c === quote && text[i - 1] !== "\\") quote = null; continue; }
    if (c === '"' || c === "'") quote = c;
    else if (c === "(" || c === "[") depth++;
    else if (c === ")" || c === "]") depth--;
    else if (c === sep && depth === 0) { parts.push(text.slice(start, i)); start = i + 1; }
  }
  parts.push(text.slice(start));
  return parts;
}

function scopeSelector(sel) {
  sel = sel.trim();
  const doc = sel.match(/^(:root|html|body)(?![\w-])/);
  if (doc) return SCOPE + sel.slice(doc[0].length);
  return `${SCOPE} ${sel}`;
}

// Walks a block body, returning the scoped text. Rules are "prelude { body }".
function scopeBlock(text) {
  let out = "", i = 0;
  while (i < text.length) {
    const open = text.indexOf("{", i);
    if (open === -1) { out += text.slice(i); break; }
    const prelude = text.slice(i, open).trim();
    let depth = 1, j = open + 1;
    for (; j < text.length && depth > 0; j++) {
      if (text[j] === "{") depth++;
      else if (text[j] === "}") depth--;
    }
    const body = text.slice(open + 1, j - 1);
    if (prelude.startsWith("@")) {
      if (!/^@media\b/.test(prelude)) throw new Error(`scope-css: unsupported at-rule "${prelude}"`);
      out += `${prelude} {\n${scopeBlock(body)}}\n`;
    } else {
      const selectors = splitTopLevel(prelude, ",").map(scopeSelector).join(",\n");
      out += `${selectors} {${body}}\n`;
    }
    i = j;
  }
  return out;
}

const header = "/* Generated by scripts/yield-calculator/scope-css.mjs from css/styles.css -- do not edit. */\n";
fs.writeFileSync(output, header + scopeBlock(css));
